### ISSUE TITLE
Menu border radius

### ISSUE THREAD

**Issue by opensw** [react-native-menu/menu#58]
Hello there, thank you for this great lib!!!

Is it possible to set the borderRadius of the popup?

**Comment by mateusz1913** [comment]
Hi, I think that's not possible for `UIMenu` (iOS), with `PopupMenu` there are 2 ways:
1) override default `PopupMenu` style in your android project's resources directory with sth like here https://stackoverflow.com/questions/12636101/how-to-style-popupmenu (to achieve border* property change, you should create background drawable and assign it to PopupMenu `android:background` style property)
2) create new menu layout which will have all custom values you want, then, that layout should be inflated with LayoutInflater - however that would require changing current PopupMenu creation logic (that library creates PopupMenu programmaticaly instead of creating it from xml resource)

**Comment by opensw** [comment]
Hi, thank you! Your first way is working (for Android, if I find a solution for iOS I am going to post here :)).

Just for reference for other users.

1. Create a drawable https://www.geeksforgeeks.org/how-to-create-drawable-resource-xml-file-in-android-studio/

2. Add your shape (change the color, corners and so on) to the generated file (mine is round_popup.xml)
```
<?xml version="1.0" encoding="utf-8"?>

<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <solid android:color="#fafafa"/>

    <corners
        android:radius="14dp"/>

    <padding
        android:bottom="14dp"
        android:top="14dp"/>

</shape>
```

3. Reference your drawable in your styles.xml

```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:textColor">#1a1a1a</item>
        <item name="android:navigationBarColor">#1a1a1a</item>

        <item name="android:popupMenuStyle">@style/RoundPopupMenuStyle</item>

    </style>

    <!-- Popup Menu Style -->
    <style name="RoundPopupMenuStyle" parent="Widget.AppCompat.PopupMenu">
        <item name="android:popupBackground">@drawable/round_popup</item>
    </style>

</resources>
```

Really thank you for the tip, this lib deserves much more popularity, it is much better than others that it is possible to find around, it is simple to use and it does not have quirks of others...
